version: '3'

networks:
  app-tier:
    driver: bridge

services:
  pr-ccmf-backend:
    image: pr-ccmf-backend
    build:
      context: ../pr-ccmf-backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-tier
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'MYSQLMCC'
      #    We cannot set user as 'root' if mysql is below version of 5.x: https://github.com/docker-library/mysql/issues/129
#      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
    networks:
      - app-tier