export const DATA_QUERY = {
    "UPDATE_USER": "UPDATE user AS u SET u.username = ?, u.password = ?, u.name=?, u.lastName =? , u.mail = ? , idRole = ? , u.phone = ?, u.status = ? WHERE u.id = ?",
    "SELECT_ID_USER": "SELECT * FROM user WHERE id = ?",
    "DELETE_USER": "DELETE FROM user WHERE id = ?",
    "INSERT_USER": "INSERT INTO user SET username = ?, password = ?, name=?, lastName =? , mail = ? , idRole = ? , phone = ?, status = ?",
    "VALIDATED_USER": "SELECT username, password FROM user WHERE username= ? AND password= ?",
    "CREATE_ROLE": "INSERT INTO role SET name=? , status=?",
    "FIND_ROLE": "SELECT * FROM role",
    "FIND_ROLE_ID": "SELECT * FROM role WHERE id = ?",
    "DELETE_ROLE_ID": "DELETE FROM role WHERE id = ?",
    "UPDATE_ROLE_ID": "UPDATE role AS r SET r.name = ? , r.status = ? WHERE id = ?",
    "INSERT_DOCUMENT": "INSERT INTO document SET name = ? , author = ?, publish = ?, idCategory = ? , description = ? , fileName = ?, filePath = ?, nameImage = ?, image = ? , status = ?",
    "FIND_DOCUMENT": "SELECT * FROM document",
    "FIND_DOCUMENT_ID": "SELECT * FROM document WHERE id = ?",
    "DELETE_DOCUMENT": "DELETE FROM document WHERE id = ?",
    "UPDATE_DOCUMENT": "UPDATE document AS d SET name = ? , author = ?, publish = ?, idCategory = ? , description = ? , fileName = ?, filePath = ?, nameImage = ?, image = ? , status = ? WHERE d.id = ?",
    "FIND_CATEGORY": "SELECT * FROM category",
    "INSERT_CATEGORY": "INSERT INTO category SET name=? , status=?",
    "UPDATE_CATEGORY": "UPDATE category SET name=?, status=?",
    "FIND_CATEGORY_ID": "SELECT * FROM category WHERE id=?",
    "DELETE_CATEGORY": "DELETE FROM category WHERE id=?",
    "FIND_EVENT": "SELECT * FROM events",
    "FIND_EVENT_ID": "SELECT * FROM event WHERE id=?",
    "INSERT_EVENT": "INSERT INTO events SET name = ? , toEvent = ? , site = ? , dateTimeEvent = ?,  contact = ? , organizedBy = ? , url = ? , resume = ? , nameImage= ? , image = ? , status = ?",
    "UPDATE_EVENT": "UPDATE events SET name = ? , to= ? , site = ? , dateTimeEvent = ?,  contact= ? , organizedBy = ? , url = ? , resume = ? , nameImage= ? , image = ? , status = ? WHERE id = ?",
    "DELETE_EVENT": "DELETE FROM events WHERE id = ?",
}